spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ciValue
    username: postgres
    password: Ram
  jpa:
    hibernate:
      ddl-auto: update
    show:
      sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect